/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf 
Author: Achie72 (https://sketchfab.com/Achie72)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/pixel-dailies-paper-8d3e9e1143ad42298fad2d48b5d1a664
Title: Pixel Dailies - Paper
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 4]}>
          <mesh geometry={nodes.Object_5.geometry} material={materials.VoxMaterial_7} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.VoxMaterial_8} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.VoxMaterial_10} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.VoxMaterial_11} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.VoxMaterial_14} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.VoxMaterial_18} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.VoxMaterial_21} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.VoxMaterial_25} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
