/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf 
Author: Mateusz Woliński (https://sketchfab.com/jeandiz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shipping-containers-cc3f7136710f4905905eae1d10ac50b7
Title: Shipping containers
*/

import React, { useRef, useState } from 'react';
import { useGLTF, Gltf } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
interface ModelProps {
    // Add any specific props that this component requires
}
export const ShippingBus: React.FC<ModelProps> = (props) => {
    const { nodes, materials }: any = useGLTF('/gltf/bus/scene.gltf');
    const [rotation, setRotation] = useState(0);
    useFrame(({ clock }) => {
        setRotation(clock.getElapsedTime() * 0.9);
    });
    return (
        <group {...props} dispose={null} rotation={[0, 100, 0]} position={[0, -1.2, 0]} scale={1.5}>
            <group position={[0.75, 0.25, -0.875]}>
                <group position={[-0.75, -0.25, 0.875]}>
                    <mesh geometry={nodes.Object_10.geometry} material={materials.material_1} />
                    <mesh geometry={nodes.Object_12.geometry} material={materials.material_1} />
                    <mesh geometry={nodes.Object_14.geometry} material={materials.material_1} />
                </group>
                <group position={[-0.75, -0.25, 0.875]}>
                    <mesh geometry={nodes.Object_17.geometry} material={materials.material_2} />
                    <mesh geometry={nodes.Object_19.geometry} material={materials.material_2} />
                </group>
                <mesh geometry={nodes.Object_7.geometry} material={materials.material_0} position={[-0.75, -0.25, 0.875]} />
            </group>
            <group position={[-0.75, 0.25, -0.938]}>
                <mesh geometry={nodes.Object_23.geometry} material={materials.material_3} position={[0.75, -0.25, 0.938]} />
            </group>
            <group position={[-0.75, 0.25, 0.938]}>
                <mesh geometry={nodes.Object_26.geometry} material={materials.material_3} position={[0.75, -0.25, -0.938]} />
            </group>
            <group position={[0.75, 0.25, 0.938]}>
                <mesh geometry={nodes.Object_29.geometry} material={materials.material_3} position={[-0.75, -0.25, -0.938]} />
            </group>
            <group position={[0.75, 0.25, -0.875]}>
                <mesh geometry={nodes.Object_32.geometry} material={materials.material_3} position={[-0.75, -0.25, 0.938]} />
            </group>
        </group>
    );
};

useGLTF.preload('/gltf/bus/scene.gltf');
