/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf 
Author: RodWay (https://sketchfab.com/rodway)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/truck-173d8b5ab74c4851a237bbad79a0d6fe
Title: Truck
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.375, 0.25, -0.625]}>
        <mesh geometry={nodes.Object_8.geometry} material={materials.material_0} position={[0, 0, 0.063]} />
      </group>
      <mesh geometry={nodes.Object_11.geometry} material={materials.material_0} position={[0.375, 0.25, -0.563]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.material_0} position={[0.375, 0.25, 0.563]} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.material_0} position={[-0.375, 0.25, 0.563]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.material_2} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
