/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf 
Author: RodWay (https://sketchfab.com/rodway)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bus-d0255220f8da4e218d0e5da5f4f3a1ca
Title: Bus
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.75, 0.25, -0.875]}>
        <group position={[-0.75, -0.25, 0.875]}>
          <mesh geometry={nodes.Object_10.geometry} material={materials.material_1} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.material_1} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.material_1} />
        </group>
        <group position={[-0.75, -0.25, 0.875]}>
          <mesh geometry={nodes.Object_17.geometry} material={materials.material_2} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.material_2} />
        </group>
        <mesh geometry={nodes.Object_7.geometry} material={materials.material_0} position={[-0.75, -0.25, 0.875]} />
      </group>
      <group position={[-0.75, 0.25, -0.938]}>
        <mesh geometry={nodes.Object_23.geometry} material={materials.material_3} position={[0.75, -0.25, 0.938]} />
      </group>
      <group position={[-0.75, 0.25, 0.938]}>
        <mesh geometry={nodes.Object_26.geometry} material={materials.material_3} position={[0.75, -0.25, -0.938]} />
      </group>
      <group position={[0.75, 0.25, 0.938]}>
        <mesh geometry={nodes.Object_29.geometry} material={materials.material_3} position={[-0.75, -0.25, -0.938]} />
      </group>
      <group position={[0.75, 0.25, -0.875]}>
        <mesh geometry={nodes.Object_32.geometry} material={materials.material_3} position={[-0.75, -0.25, 0.938]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
