/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf 
Author: MaxDeaconVR (https://sketchfab.com/MaxDeaconVR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/asriels-pc-deltaex-visuals-genesis-217be3bc57cc450ba840debb4c62cbb3
Title: Asriel's PC (DeltaEx - Visuals Genesis)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.969}>
        <group position={[-5.193, -0.126, 0.475]} rotation={[0, 0, -Math.PI]} scale={0.01}>
          <mesh geometry={nodes.Kris_Room006_0.geometry} material={materials.obvodka} />
          <mesh geometry={nodes.Kris_Room006_1.geometry} material={materials.Wood_Brown1} />
          <mesh geometry={nodes.Kris_Room006_2.geometry} material={materials.Pillow} />
          <mesh geometry={nodes.Kris_Room006_3.geometry} material={materials.Lamp_warmgray} />
          <mesh geometry={nodes.Kris_Room006_4.geometry} material={materials.Lamp_lightgray} />
          <mesh geometry={nodes.Kris_Room006_5.geometry} material={materials.Gray_shadow} />
        </group>
        <group position={[-2.673, 0.162, 0.602]} rotation={[Math.PI / 2, -0.095, 0]} scale={0.008}>
          <mesh geometry={nodes.Monitor_0.geometry} material={materials.keyb_mouse} />
          <mesh geometry={nodes.Monitor_1.geometry} material={materials.Display} />
        </group>
        <group position={[-3.916, -2.801, 0.706]} rotation={[0, 0, -Math.PI]} scale={0.01}>
          <mesh geometry={nodes.Kris_Room001_0.geometry} material={materials['obvodka.004']} />
          <mesh geometry={nodes.Kris_Room001_1.geometry} material={materials['Wood_Brown1.001']} />
          <mesh geometry={nodes.Kris_Room001_2.geometry} material={materials['Pillow.001']} />
          <mesh geometry={nodes.Kris_Room001_3.geometry} material={materials['Lamp_warmgray.001']} />
          <mesh geometry={nodes.Kris_Room001_4.geometry} material={materials['Gray_shadow.001']} />
        </group>
        <group scale={[0.009, 0.009, 0.01]}>
          <mesh geometry={nodes.NGon001_0.geometry} material={materials.Electronics1} />
          <mesh geometry={nodes.NGon001_1.geometry} material={materials.Wood_Top} />
          <mesh geometry={nodes.NGon001_2.geometry} material={materials.Wooden_Sides} />
        </group>
        <mesh geometry={nodes.Keyb_mouse_0.geometry} material={materials.keyb_mouse} position={[-2.786, -0.117, 0.499]} scale={0.005} />
        <mesh geometry={nodes.NGon001001_0.geometry} material={materials.Carpet} scale={[0.009, 0.009, 0.01]} />
        <mesh geometry={nodes.NGon001002_0.geometry} material={materials.Carpet} position={[-2.585, 0, 0]} scale={[0.009, 0.009, 0.01]} />
        <mesh geometry={nodes.NGon001003_0.geometry} material={materials.Carpet} position={[-5.159, 0, 0]} scale={[0.009, 0.009, 0.01]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
