/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf 
Author: Imad Hassan (https://sketchfab.com/imad.hassan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/a-rainy-day-577d410f936d4dd185b92c3c79e07bb2
Title: A Rainy Day
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[4.216, -0.959, 2.133]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.086, 0.161, 0.077]}>
        <mesh geometry={nodes.Object_16.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.176, 4.33, 0.462]} scale={[1.105, 1.153, 1.44]}>
        <mesh geometry={nodes.Object_20.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-3.535, -0.765, 0.603]} scale={[0.102, 0.352, 1]}>
        <mesh geometry={nodes.Object_24.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Object_25.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.429, -0.321, 1.327]} scale={[0.077, 0.8, 0.203]}>
        <mesh geometry={nodes.Object_28.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Object_29.geometry} material={materials['Material.002']} />
      </group>
      <group position={[1.814, 0.535, 1.332]}>
        <mesh geometry={nodes.Object_49.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Object_50.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-0.386, 10.9, 1.729]} rotation={[-0.484, 0.552, -0.581]} scale={0.655}>
        <mesh geometry={nodes.Object_200.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Object_201.geometry} material={materials['Material.026']} />
      </group>
      <group position={[-3.745, 9.019, 0.08]} rotation={[-0.462, -0.475, -1.074]} scale={0.655}>
        <mesh geometry={nodes.Object_203.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Object_204.geometry} material={materials['Material.026']} />
      </group>
      <group position={[2.951, 8.544, 2.896]} rotation={[-2.733, -0.069, 2.321]} scale={0.655}>
        <mesh geometry={nodes.Object_206.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Object_207.geometry} material={materials['Material.026']} />
      </group>
      <group position={[-6.853, -0.755, -1.85]} scale={0.385}>
        <mesh geometry={nodes.Object_227.geometry} material={materials['Material.032']} />
        <mesh geometry={nodes.Object_228.geometry} material={materials['Material.036']} />
      </group>
      <group position={[-6.855, 4.252, -2.264]} rotation={[-Math.PI, 0, 0]} scale={[-0.026, 0.467, 0.297]}>
        <mesh geometry={nodes.Object_232.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Object_233.geometry} material={materials['Material.035']} />
        <mesh geometry={nodes.Object_234.geometry} material={materials['Material.037']} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.006']} position={[-0.178, -0.211, -0.52]} rotation={[0, -0.356, 0]} scale={[0.523, 0.565, 0.397]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.006']} position={[-0.099, 1.19, -0.664]} rotation={[-0.402, -0.33, -0.137]} scale={[0.778, 0.668, 0.381]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.007']} position={[-0.132, 1.108, -0.642]} rotation={[-0.402, -0.33, -0.137]} scale={[0.98, 0.676, 0.559]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.006']} position={[-0.316, -0.948, -0.613]} rotation={[0, -0.356, 0]} scale={[0.629, 0.659, 0.5]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['Material.018']} position={[-0.146, -0.737, 0.39]} rotation={[-1.182, -0.602, 1.643]} scale={0.816} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Material.007']} position={[0.449, 1.599, -0.686]} rotation={[-0.402, -0.33, -0.666]} scale={[0.337, 0.337, 0.09]} />
      <mesh geometry={nodes.Object_31.geometry} material={materials['Material.001']} position={[-0.136, -1.14, -3.778]} />
      <mesh geometry={nodes.Object_33.geometry} material={materials['Material.001']} position={[4.733, -1.14, -1.658]} rotation={[0, -0.822, 0]} scale={0.545} />
      <mesh geometry={nodes.Object_35.geometry} material={materials['Material.001']} position={[-6.174, -1.14, -1.76]} rotation={[-Math.PI, 1.461, -Math.PI]} />
      <mesh geometry={nodes.Object_37.geometry} material={materials['Material.001']} position={[5.691, -1.14, 6.557]} rotation={[0, -1.414, 0]} />
      <mesh geometry={nodes.Object_39.geometry} material={materials['Material.001']} position={[-4.539, -1.14, 4.737]} rotation={[0, -1.414, 0]} />
      <mesh geometry={nodes.Object_41.geometry} material={materials['Material.001']} position={[-2.843, -1.14, 4.737]} rotation={[-Math.PI, 0.431, -Math.PI]} scale={0.393} />
      <mesh geometry={nodes.Object_43.geometry} material={materials['Material.001']} position={[-2.813, -1.14, -2.989]} rotation={[-Math.PI, 1.169, Math.PI]} scale={0.393} />
      <mesh geometry={nodes.Object_45.geometry} material={materials['Material.005']} position={[4.397, -1.183, 2.218]} rotation={[-2.874, -1.245, -1.787]} scale={[0.448, 0.448, 0.074]} />
      <mesh geometry={nodes.Object_47.geometry} material={materials['Material.008']} position={[4.437, -1.183, 2.218]} rotation={[-0.294, 1.406, 1.434]} scale={[0.608, 0.608, 0.101]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials['Material.017']} position={[-0.099, 1.19, -0.664]} rotation={[-0.402, -0.33, -0.137]} scale={[0.778, 0.668, 0.381]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials['Material.009']} position={[0.062, 1.296, -1.075]} rotation={[-0.67, 0.28, -1.175]} scale={0.209} />
      <mesh geometry={nodes.Object_56.geometry} material={materials['Material.010']} position={[0.216, 1.048, -0.974]} rotation={[-0.287, -0.454, -0.208]} scale={[0.124, 0.124, 0.035]} />
      <mesh geometry={nodes.Object_58.geometry} material={materials['Material.011']} position={[0.036, 0.898, -1.032]} rotation={[-0.595, -0.299, -0.197]} scale={[0.022, 0.02, 0.009]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials['Material.010']} position={[0.072, 0.869, -1.01]} rotation={[-0.288, -0.343, -0.736]} scale={0.03} />
      <mesh geometry={nodes.Object_62.geometry} material={materials['Material.010']} position={[-0.002, 0.869, -1.038]} rotation={[2.854, 0.343, 2.604]} scale={0.03} />
      <mesh geometry={nodes.Object_64.geometry} material={materials['Material.010']} position={[0.489, 0.932, -0.745]} rotation={[-0.375, 0.008, 0.244]} scale={0.137} />
      <mesh geometry={nodes.Object_66.geometry} material={materials['Material.010']} position={[0.482, 0.866, -0.715]} rotation={[-0.275, -0.125, -0.047]} scale={[0.124, 0.137, 0.137]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials['Material.010']} position={[0.433, 0.788, -0.7]} rotation={[0.348, -0.337, -0.207]} scale={0.137} />
      <mesh geometry={nodes.Object_70.geometry} material={materials['Material.010']} position={[-0.477, 0.935, -1.094]} rotation={[2.968, 0.665, -2.781]} scale={0.137} />
      <mesh geometry={nodes.Object_72.geometry} material={materials['Material.010']} position={[-0.487, 0.868, -1.069]} rotation={[2.842, 0.543, -2.99]} scale={[0.124, 0.137, 0.137]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials['Material.010']} position={[-0.457, 0.788, -1.03]} rotation={[2.097, 0.531, -2.908]} scale={0.137} />
      <mesh geometry={nodes.Object_76.geometry} material={materials['Material.010']} position={[-0.133, 1.044, -1.122]} rotation={[-0.262, -0.231, -0.168]} scale={[0.124, 0.124, 0.035]} />
      <mesh geometry={nodes.Object_78.geometry} material={materials['Material.012']} position={[0.213, 1.074, -1.015]} rotation={[-0.379, -0.452, -0.242]} scale={[0.051, 0.051, 0.014]} />
      <mesh geometry={nodes.Object_80.geometry} material={materials['Material.012']} position={[0.29, 1.097, -0.973]} rotation={[0.086, -0.883, -0.112]} scale={[0.015, 0.015, 0.004]} />
      <mesh geometry={nodes.Object_82.geometry} material={materials['Material.012']} position={[-0.082, 1.07, -1.14]} rotation={[2.92, 0.467, 3.107]} scale={[0.051, 0.051, 0.014]} />
      <mesh geometry={nodes.Object_84.geometry} material={materials['Material.012']} position={[-0.166, 1.091, -1.165]} rotation={[2.964, 0.172, -3.09]} scale={[0.015, 0.015, 0.004]} />
      <mesh geometry={nodes.Object_86.geometry} material={materials['Material.019']} position={[-0.127, 0.194, -0.487]} rotation={[0, -0.356, 0]} scale={0.488} />
      <mesh geometry={nodes.Object_88.geometry} material={materials['Material.004']} position={[4.161, 2.002, 0.545]} rotation={[0, 0, -Math.PI / 2]} scale={[2.353, 1.003, 1.634]} />
      <mesh geometry={nodes.Object_90.geometry} material={materials['Material.004']} position={[1.501, 1.898, 2.122]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[2.384, 1.003, 2.613]} />
      <mesh geometry={nodes.Object_92.geometry} material={materials['Material.004']} position={[-3.58, 1.731, 0.6]} rotation={[0, 0, -Math.PI / 2]} scale={[1.751, 1.003, 1.243]} />
      <mesh geometry={nodes.Object_94.geometry} material={materials['Material.006']} position={[0.088, -0.948, -0.462]} rotation={[0, -0.356, 0]} scale={[0.629, 0.659, 0.5]} />
      <mesh geometry={nodes.Object_96.geometry} material={materials['Material.021']} position={[2.962, 2.699, 2.109]} rotation={[Math.PI / 2, 0, 0]} scale={0.801} />
      <mesh geometry={nodes.Object_98.geometry} material={materials['Material.022']} position={[0.09, 0.343, -0.851]} rotation={[0.521, -0.385, 0.341]} scale={[0.031, 0.031, 0.009]} />
      <mesh geometry={nodes.Object_100.geometry} material={materials['Material.022']} position={[0.117, 0.185, -0.913]} rotation={[0.378, -0.463, 0.117]} scale={[0.031, 0.031, 0.009]} />
      <mesh geometry={nodes.Object_102.geometry} material={materials['Material.022']} position={[0.137, 0.013, -0.977]} rotation={[0.378, -0.463, 0.117]} scale={[0.031, 0.031, 0.009]} />
      <mesh geometry={nodes.Object_104.geometry} material={materials['Material.007']} position={[-0.561, 1.562, -1.066]} rotation={[-0.311, -0.45, 0.839]} scale={[0.337, 0.337, 0.09]} />
      <mesh geometry={nodes.Object_106.geometry} material={materials['Material.023']} position={[3.162, 2.44, -4.604]} rotation={[0.68, 0, 0]} scale={[0.028, 0.238, 0.028]} />
      <mesh geometry={nodes.Object_108.geometry} material={materials['Material.023']} position={[5.284, 4.864, -3.439]} rotation={[0.68, 0, 0]} scale={[0.028, 0.238, 0.028]} />
      <mesh geometry={nodes.Object_110.geometry} material={materials['Material.023']} position={[-1.909, 2.584, -3.439]} rotation={[0.68, 0, 0]} scale={[0.025, 0.213, 0.025]} />
      <mesh geometry={nodes.Object_112.geometry} material={materials['Material.023']} position={[-7.077, 0.185, -4.604]} rotation={[0.68, 0, 0]} scale={[0.028, 0.238, 0.028]} />
      <mesh geometry={nodes.Object_114.geometry} material={materials['Material.023']} position={[4.106, 7.554, -3.439]} rotation={[0.68, 0, 0]} scale={[0.018, 0.148, 0.018]} />
      <mesh geometry={nodes.Object_116.geometry} material={materials['Material.023']} position={[-4.4, 7.231, -3.439]} rotation={[0.68, 0, 0]} scale={[0.018, 0.148, 0.018]} />
      <mesh geometry={nodes.Object_118.geometry} material={materials['Material.023']} position={[3.965, 1.831, 5.831]} rotation={[0.68, 0, 0]} scale={[0.028, 0.238, 0.028]} />
      <mesh geometry={nodes.Object_120.geometry} material={materials['Material.023']} position={[2.68, 4.422, 5.831]} rotation={[0.68, 0, 0]} scale={[0.028, 0.238, 0.028]} />
      <mesh geometry={nodes.Object_122.geometry} material={materials['Material.023']} position={[5.872, 4.795, 5.831]} rotation={[0.68, 0, 0]} scale={[0.028, 0.238, 0.028]} />
      <mesh geometry={nodes.Object_124.geometry} material={materials['Material.023']} position={[-0.201, 5.293, 5.831]} rotation={[0.68, 0, 0]} scale={[0.028, 0.238, 0.028]} />
      <mesh geometry={nodes.Object_126.geometry} material={materials['Material.023']} position={[-1.321, 2.515, 5.831]} rotation={[0.68, 0, 0]} scale={[0.028, 0.238, 0.028]} />
      <mesh geometry={nodes.Object_128.geometry} material={materials['Material.023']} position={[1.312, 0.546, 5.831]} rotation={[0.68, 0, 0]} scale={[0.028, 0.238, 0.028]} />
      <mesh geometry={nodes.Object_130.geometry} material={materials['Material.023']} position={[-6.275, 1.39, 5.906]} rotation={[0.41, 0, 0]} scale={[0.028, 0.238, 0.028]} />
      <mesh geometry={nodes.Object_132.geometry} material={materials['Material.023']} position={[6.933, 1.466, 5.831]} rotation={[0.68, 0, 0]} scale={[0.028, 0.238, 0.028]} />
      <mesh geometry={nodes.Object_134.geometry} material={materials['Material.023']} position={[5.291, 7.178, 1.949]} rotation={[0.68, 0, 0]} scale={[0.018, 0.148, 0.018]} />
      <mesh geometry={nodes.Object_136.geometry} material={materials['Material.023']} position={[-0.858, 6.461, 2.094]} rotation={[0.68, 0, 0]} scale={[0.028, 0.238, 0.028]} />
      <mesh geometry={nodes.Object_138.geometry} material={materials['Material.023']} position={[-1.977, 6.284, 2.094]} rotation={[0.68, 0, 0]} scale={[0.018, 0.148, 0.018]} />
      <mesh geometry={nodes.Object_140.geometry} material={materials['Material.023']} position={[0.655, 6.564, 2.094]} rotation={[0.68, 0, 0]} scale={[0.018, 0.148, 0.018]} />
      <mesh geometry={nodes.Object_142.geometry} material={materials['Material.023']} position={[-6.931, 5.594, 2.094]} rotation={[0.68, 0, 0]} scale={[0.028, 0.238, 0.028]} />
      <mesh geometry={nodes.Object_144.geometry} material={materials['Material.023']} position={[6.355, 6.837, 1.904]} rotation={[0.68, 0, 0]} scale={[0.018, 0.148, 0.018]} />
      <mesh geometry={nodes.Object_146.geometry} material={materials['Material.023']} position={[-4.355, 7.515, 1.939]} rotation={[0.68, 0, 0]} scale={[0.028, 0.238, 0.028]} />
      <mesh geometry={nodes.Object_148.geometry} material={materials['Material.023']} position={[2.059, 3.875, -4.639]} rotation={[0.68, 0, 0]} scale={[0.028, 0.238, 0.028]} />
      <mesh geometry={nodes.Object_150.geometry} material={materials['Material.023']} position={[-0.822, 4.746, -4.639]} rotation={[0.68, 0, 0]} scale={[0.025, 0.213, 0.025]} />
      <mesh geometry={nodes.Object_152.geometry} material={materials['Material.023']} position={[-2.156, 2.508, -5.804]} rotation={[0.68, 0, 0]} scale={[0.025, 0.213, 0.025]} />
      <mesh geometry={nodes.Object_154.geometry} material={materials['Material.023']} position={[0.539, 0.455, -5.471]} rotation={[0.68, 0, 0]} scale={[0.028, 0.238, 0.028]} />
      <mesh geometry={nodes.Object_156.geometry} material={materials['Material.023']} position={[-6.973, -0.818, -5.061]} rotation={[0.68, 0, 0]} scale={[0.028, 0.238, 0.028]} />
      <mesh geometry={nodes.Object_158.geometry} material={materials['Material.023']} position={[-4.433, 6.615, -4.639]} rotation={[0.68, 0, 0]} scale={[0.016, 0.132, 0.016]} />
      <mesh geometry={nodes.Object_160.geometry} material={materials['Material.023']} position={[3.076, 3.37, -6.58]} rotation={[0.68, 0, 0]} scale={[0.025, 0.213, 0.025]} />
      <mesh geometry={nodes.Object_162.geometry} material={materials['Material.023']} position={[1.791, 5.961, -6.58]} rotation={[0.68, 0, 0]} scale={[0.025, 0.213, 0.025]} />
      <mesh geometry={nodes.Object_164.geometry} material={materials['Material.023']} position={[4.983, 6.334, -6.58]} rotation={[0.68, 0, 0]} scale={[0.025, 0.213, 0.025]} />
      <mesh geometry={nodes.Object_166.geometry} material={materials['Material.023']} position={[-1.09, 6.831, -6.58]} rotation={[0.68, 0, 0]} scale={[0.018, 0.148, 0.018]} />
      <mesh geometry={nodes.Object_168.geometry} material={materials['Material.023']} position={[0.423, 2.085, -6.58]} rotation={[0.68, 0, 0]} scale={[0.025, 0.213, 0.025]} />
      <mesh geometry={nodes.Object_170.geometry} material={materials['Material.023']} position={[-7.163, 1.115, -6.58]} rotation={[0.68, 0, 0]} scale={[0.025, 0.213, 0.025]} />
      <mesh geometry={nodes.Object_172.geometry} material={materials['Material.023']} position={[-4.701, 8.701, -6.58]} rotation={[0.68, 0, 0]} scale={[0.018, 0.148, 0.018]} />
      <mesh geometry={nodes.Object_174.geometry} material={materials['Material.023']} position={[3.155, 5.634, -0.3]} rotation={[0.68, 0, 0]} scale={[0.018, 0.148, 0.018]} />
      <mesh geometry={nodes.Object_176.geometry} material={materials['Material.023']} position={[1.87, 5.625, -0.3]} rotation={[0.68, 0, 0]} scale={[0.018, 0.148, 0.018]} />
      <mesh geometry={nodes.Object_178.geometry} material={materials['Material.023']} position={[-2.13, 6.318, -0.3]} rotation={[0.68, 0, 0]} scale={[0.018, 0.148, 0.018]} />
      <mesh geometry={nodes.Object_180.geometry} material={materials['Material.023']} position={[0.502, 6.598, -0.3]} rotation={[0.68, 0, 0]} scale={[0.018, 0.148, 0.018]} />
      <mesh geometry={nodes.Object_182.geometry} material={materials['Material.023']} position={[-7.084, 5.628, -0.3]} rotation={[0.68, 0, 0]} scale={[0.028, 0.238, 0.028]} />
      <mesh geometry={nodes.Object_184.geometry} material={materials['Material.023']} position={[6.237, 6.703, -0.456]} rotation={[0.68, 0, 0]} scale={[0.018, 0.148, 0.018]} />
      <mesh geometry={nodes.Object_186.geometry} material={materials['Material.023']} position={[-4.622, 8.017, -0.3]} rotation={[0.68, 0, 0]} scale={[0.028, 0.238, 0.028]} />
      <mesh geometry={nodes.Object_188.geometry} material={materials['Material.001']} position={[-1.207, 4.54, 0.55]} rotation={[-Math.PI, -0.52, -Math.PI]} />
      <mesh geometry={nodes.Object_190.geometry} material={materials['Material.001']} position={[1.866, 4.535, 0.771]} rotation={[0, -1.414, 0]} />
      <mesh geometry={nodes.Object_192.geometry} material={materials['Material.024']} position={[1.895, 4.654, 1.164]} scale={0.026} />
      <mesh geometry={nodes.Object_194.geometry} material={materials['Material.024']} position={[1.846, 4.746, 1.068]} scale={0.016} />
      <mesh geometry={nodes.Object_196.geometry} material={materials['Material.024']} position={[1.792, 4.648, 1.003]} scale={0.016} />
      <mesh geometry={nodes.Object_198.geometry} material={materials['Material.023']} position={[1.8, 4.701, 1.165]} rotation={[0.68, 0, 0]} scale={[0.014, 0.117, 0.014]} />
      <mesh geometry={nodes.Object_209.geometry} material={materials['Material.005']} position={[4.481, -1.183, 2.218]} rotation={[-3.056, -0.18, -2.026]} scale={[0.296, 0.296, 0.049]} />
      <mesh geometry={nodes.Object_211.geometry} material={materials['Material.008']} position={[4.521, -1.183, 2.218]} rotation={[-0.05, 0.337, 1.161]} scale={[0.402, 0.402, 0.067]} />
      <mesh geometry={nodes.Object_213.geometry} material={materials['Material.005']} position={[-4.254, -1.183, -0.237]} rotation={[-3.055, -0.215, -2.023]} scale={[0.476, 0.476, 0.079]} />
      <mesh geometry={nodes.Object_215.geometry} material={materials['Material.008']} position={[-4.214, -1.183, -0.237]} rotation={[-0.051, 0.372, 1.163]} scale={[0.647, 0.647, 0.107]} />
      <mesh geometry={nodes.Object_217.geometry} material={materials['Material.005']} position={[-4.17, -1.183, -0.237]} rotation={[-3.012, 0.856, -2.139]} scale={[0.314, 0.314, 0.052]} />
      <mesh geometry={nodes.Object_219.geometry} material={materials['Material.008']} position={[-4.13, -1.183, -0.237]} rotation={[-0.062, -0.702, 1.104]} scale={[0.427, 0.427, 0.071]} />
      <mesh geometry={nodes.Object_221.geometry} material={materials['Material.016']} position={[2.962, 2.699, 2.113]} rotation={[Math.PI / 2, 0, 0]} scale={0.801} />
      <mesh geometry={nodes.Object_223.geometry} material={materials['Material.027']} position={[-3.592, 2.054, 0.139]} rotation={[0.083, 0, -Math.PI / 2]} scale={[0.637, 0.537, 0.532]} />
      <mesh geometry={nodes.Object_225.geometry} material={materials['Material.029']} position={[-3.592, 1.188, 1.078]} rotation={[0.508, 0, -Math.PI / 2]} scale={[0.393, 0.331, 0.328]} />
      <mesh geometry={nodes.Object_230.geometry} material={materials['Material.033']} position={[-6.854, 5.596, -1.849]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.219, 0.024, 0.219]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
