/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf 
Author: arogeek (https://sketchfab.com/arogeek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/facebook-61a3637914844efd808b9a14c67b6c29
Title: FACEBOOK
*/

import React, { useRef, useState } from 'react';
import { useGLTF, Gltf } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

interface ModelProps {
    // Add any specific props that this component requires
}

export const Truck: React.FC<ModelProps> = (props) => {
    const { nodes, materials }: any = useGLTF('/gltf/truck/scene.gltf');
    const [rotation, setRotation] = useState(0);
    useFrame(({ clock }) => {
        setRotation(clock.getElapsedTime() * 0.9);
    });
    return (
        <group {...props} dispose={null} rotation={[0, 100, 0]} scale={2.3} position={[0, -1.2, 0]}>
            <group position={[-0.375, 0.25, -0.625]}>
                <mesh geometry={nodes.Object_8.geometry} material={materials.material_0} position={[0, 0, 0.063]} />
            </group>
            <mesh geometry={nodes.Object_11.geometry} material={materials.material_0} position={[0.375, 0.25, -0.563]} />
            <mesh geometry={nodes.Object_14.geometry} material={materials.material_0} position={[0.375, 0.25, 0.563]} />
            <mesh geometry={nodes.Object_17.geometry} material={materials.material_0} position={[-0.375, 0.25, 0.563]} />
            <mesh geometry={nodes.Object_20.geometry} material={materials.material_1} />
            <mesh geometry={nodes.Object_22.geometry} material={materials.material_1} />
            <mesh geometry={nodes.Object_24.geometry} material={materials.material_2} />
        </group>
    );
};

useGLTF.preload('/gltf/truck/scene.gltf');
