/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf 
Author: arogeek (https://sketchfab.com/arogeek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/facebook-61a3637914844efd808b9a14c67b6c29
Title: FACEBOOK
*/

import React, { useRef, useState } from 'react';
import { useGLTF, Gltf } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

interface ModelProps {
    // Add any specific props that this component requires
}

export const Note: React.FC<ModelProps> = (props) => {
    const { nodes, materials }: any = useGLTF('/note/scene.gltf');
    const [rotation, setRotation] = useState(0);
    useFrame(({ clock }) => {
        setRotation(clock.getElapsedTime() * 0.9);
    });
    return (
        <group {...props} dispose={null} position={[-6, -10, -6]} scale={1.5}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group position={[0, 0, 4]}>
                    <mesh geometry={nodes.Object_5.geometry} material={materials.VoxMaterial_7} />
                    <mesh geometry={nodes.Object_6.geometry} material={materials.VoxMaterial_8} />
                    <mesh geometry={nodes.Object_7.geometry} material={materials.VoxMaterial_10} />
                    <mesh geometry={nodes.Object_8.geometry} material={materials.VoxMaterial_11} />
                    <mesh geometry={nodes.Object_9.geometry} material={materials.VoxMaterial_14} />
                    <mesh geometry={nodes.Object_10.geometry} material={materials.VoxMaterial_18} />
                    <mesh geometry={nodes.Object_11.geometry} material={materials.VoxMaterial_21} />
                    <mesh geometry={nodes.Object_12.geometry} material={materials.VoxMaterial_25} />
                </group>
            </group>
        </group>
    );
};

useGLTF.preload('/note/scene.gltf');
